FROM node:24
WORKDIR /app

COPY ./package-lock.json .
COPY ./package.json .
COPY ./.npmrc .
RUN npm ci

COPY ./tsconfig.json .
COPY ./tsconfig.node.json .
COPY ./tsconfig.app.json .
COPY ./vite.config.ts .
COPY ./testSetup.ts .
COPY ./index.html .
COPY ./src ./src
COPY ./public ./public

CMD npx vite --host
