FROM node:24
USER node
WORKDIR /home/node/app

COPY --chown=node:node ./package-lock.json .
COPY --chown=node:node ./package.json .
COPY --chown=node:node ./.npmrc .
RUN npm ci

COPY --chown=node:node ./tsconfig.json .
COPY --chown=node:node ./tsconfig.node.json .
COPY --chown=node:node ./tsconfig.app.json .
COPY --chown=node:node ./vite.config.ts .
COPY --chown=node:node ./testSetup.ts .
COPY --chown=node:node ./index.html .
COPY --chown=node:node ./src ./src
COPY --chown=node:node ./public ./public
COPY --chown=node:node ./test ./test

CMD npx vitest run
