# PG_URI: postgres://postgres:postgres@localhost:5555/devdb

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devdb
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3001:3001
    environment:
      PG_URI: postgres://postgres:postgres@postgres:5432/devdb
      NODE_ENV: development
      DATABASE_PASSWORD: AAA
      START_YEAR: 2024

volumes:
  pgdata:
    driver: local