version: "2"
services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    expose:
      - 5432
  unit_tests:
    build:
      context: .
    environment:
      PG_URI: postgres://postgres:postgres@postgres:5432/testdb
      NODE_ENV: test
    depends_on:
      - postgres
  